version: "3.9"

services:
  notes-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: notes-api

    ports:
      - "8080:8080"

    environment:
      PORT: 8080
      RATE_LIMIT_MAX: 60
      RATE_LIMIT_WINDOW_SEC: 60
      API_KEYS: sandbox_key:standard_key:enhanced_key:enterprise_key

    restart: unless-stopped
